name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: go mod download
      - name: Build binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o complete-command ./...
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: complete-command
          path: complete-command
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: complete-command
